spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

mybatis:
  type-aliases-package: com.world.playstay.*.mapper
  mapper-locations: mybatis/mapper/*.xml

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:info}
  dir:
    ./logs